name: Unspecified
favicon: null
layout_spectrum: 0.2915584046859294
typography_spectrum: 0.7216238661203533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8645059571135789
  lightness: 0.1687325716484338
  saturation: 0.4702076897956431
  rhythmicContrast: 0.7449406317900866
purpose: []
